from pathlib import Path

from handbrake.models.preset import Preset

sample_video_path = Path(__file__).parent / "sample.mp4"

sample_preset = Preset(
    preset_list=[
        {
            "AlignAVStart": False,
            "AudioCopyMask": [
                "copy:aac",
                "copy:ac3",
                "copy:eac3",
                "copy:dtshd",
                "copy:dts",
                "copy:mp3",
                "copy:truehd",
                "copy:flac",
            ],
            "AudioEncoderFallback": "av_aac",
            "AudioLanguageList": [],
            "AudioList": [
                {
                    "AudioBitrate": 128,
                    "AudioCompressionLevel": -1.0,
                    "AudioDitherMethod": "auto",
                    "AudioEncoder": "av_aac",
                    "AudioMixdown": "dpl2",
                    "AudioNormalizeMixLevel": False,
                    "AudioSamplerate": "auto",
                    "AudioTrackDRCSlider": 0.0,
                    "AudioTrackGainSlider": 0.0,
                    "AudioTrackQuality": -1.0,
                    "AudioTrackQualityEnable": False,
                }
            ],
            "AudioSecondaryEncoderMode": True,
            "AudioTrackSelectionBehavior": "first",
            "ChapterMarkers": True,
            "ChildrenArray": [],
            "Default": True,
            "FileFormat": "av_mp4",
            "Folder": False,
            "FolderOpen": False,
            "InlineParameterSets": False,
            "MetadataPassthrough": True,
            "Mp4iPodCompatible": False,
            "Optimize": False,
            "PictureAllowUpscaling": False,
            "PictureAutoCrop": True,
            "PictureBottomCrop": 0,
            "PictureChromaSmoothCustom": "",
            "PictureChromaSmoothPreset": "off",
            "PictureChromaSmoothTune": "none",
            "PictureColorspaceCustom": "",
            "PictureColorspacePreset": "off",
            "PictureCombDetectCustom": "",
            "PictureCombDetectPreset": "off",
            "PictureCropMode": 0,
            "PictureDARWidth": 0,
            "PictureDeblockCustom": "strength=strong:thresh=20:blocksize=8",
            "PictureDeblockPreset": "off",
            "PictureDeblockTune": "medium",
            "PictureDeinterlaceCustom": "",
            "PictureDeinterlaceFilter": "off",
            "PictureDeinterlacePreset": "default",
            "PictureDenoiseCustom": "",
            "PictureDenoiseFilter": "off",
            "PictureDenoisePreset": "medium",
            "PictureDenoiseTune": "none",
            "PictureDetelecine": "off",
            "PictureDetelecineCustom": "",
            "PictureForceHeight": 0,
            "PictureForceWidth": 0,
            "PictureHeight": 0,
            "PictureItuPAR": False,
            "PictureKeepRatio": True,
            "PictureLeftCrop": 0,
            "PictureModulus": 2,
            "PicturePAR": "auto",
            "PicturePARHeight": 720,
            "PicturePARWidth": 853,
            "PicturePadBottom": 0,
            "PicturePadColor": "black",
            "PicturePadLeft": 0,
            "PicturePadMode": "none",
            "PicturePadRight": 0,
            "PicturePadTop": 0,
            "PictureRightCrop": 0,
            "PictureRotate": "angle=0:hflip=0",
            "PictureSharpenCustom": "",
            "PictureSharpenFilter": "off",
            "PictureSharpenPreset": "medium",
            "PictureSharpenTune": "none",
            "PictureTopCrop": 0,
            "PictureUseMaximumSize": True,
            "PictureWidth": 0,
            "PresetDescription": "",
            "PresetDisabled": False,
            "PresetName": "pytest",
            "SubtitleAddCC": False,
            "SubtitleAddForeignAudioSearch": False,
            "SubtitleAddForeignAudioSubtitle": False,
            "SubtitleBurnBDSub": False,
            "SubtitleBurnBehavior": "none",
            "SubtitleBurnDVDSub": False,
            "SubtitleLanguageList": [],
            "SubtitleTrackSelectionBehavior": "none",
            "Type": 0,
            "UsesPictureFilters": True,
            "VideoAvgBitrate": 6000,
            "VideoColorMatrixCodeOverride": 0,
            "VideoEncoder": "x264",
            "VideoFramerate": "auto",
            "VideoFramerateMode": "vfr",
            "VideoGrayScale": False,
            "VideoHWDecode": 0,
            "VideoLevel": "auto",
            "VideoMultiPass": False,
            "VideoOptionExtra": "",
            "VideoPreset": "medium",
            "VideoProfile": "auto",
            "VideoQSVDecode": False,
            "VideoQualitySlider": 22.0,
            "VideoQualityType": 2,
            "VideoScaler": "swscale",
            "VideoTune": "",
            "VideoTurboMultiPass": False,
            "x264Option": "",
            "x264UseAdvancedOptions": False,
        }
    ],
    version_major=53,
    version_micro=0,
    version_minor=0,
)
