name: build

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build_wheel:
    name: Build wheel
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pipx install poetry
      - name: Build wheel
        run: poetry build -f wheel
      - uses: actions/upload-artifact@v4
        with:
          name: dist-wheel
          path: ./dist/*.whl

  build_sdist:
    name: Build source distribution
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pipx install poetry
      - name: Build sdist
        run: poetry build -f sdist
      - uses: actions/upload-artifact@v4
        with:
          name: dist-sdist
          path: dist/*.tar.gz
