name: deploy

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: [build_and_test]
    environment: deploy_pypi
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
