name: test

on: [workflow_call]

jobs:
  lint:
    name: Lint Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pipx install poetry
      - name: Install pyhandbrake
        run: poetry install
      - name: Run MyPy
        run: make lint

  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pipx install black isort
      - name: Check import sorting
        run: isort --tc --profile black --check-only .
      - name: Check black formatting
        run: black --check .

  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install handbrake
        run: sudo apt-get update && sudo apt-get install -y handbrake-cli
      - name: Install pyhandbrake
        run: poetry install
      - name: Run tests
        run: make test

  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install handbrake
        run: |
          Invoke-WebRequest https://github.com/HandBrake/HandBrake/releases/download/1.10.2/HandBrakeCLI-1.10.2-win-x86_64.zip -OutFile ./handbrakecli.zip
          Expand-Archive -Path ./handbrakecli.zip -DestinationPath C:/
          echo "C:\Users\runneradmin\.local\bin" >> "$GITHUB_PATH"
      - name: Install pyhandbrake
        run: C:\Users\runneradmin\.local\bin\poetry install
      - name: Run tests
        run: |
          C:\Users\runneradmin\.local\bin\poetry run coverage run -m pytest tests/
          C:\Users\runneradmin\.local\bin\poetry run coverage report

  test-macos:
    name: Test macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Install handbrake
        run: brew install handbrake
      - name: Install pyhandbrake
        run: poetry install
      - name: Run tests
        run: make test
